server:
  port: 8082
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:./.local-db/statistics
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /db
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: customer-statistics
      auto-offset-reset: earliest
      properties:
        "[spring.json.use.type.headers]": false
        "[spring.json.value.default.type]": de.sample.schulung.statistics.kafka.CustomerEventRecord
        # Parameters for ErrorHandlingDeserializer
        "[spring.deserializer.value.delegate.class]": de.sample.schulung.statistics.kafka.CustomJsonDeserializer
        "[spring.deserializer.value.function]": de.sample.schulung.statistics.kafka.exceptions.CustomDeserializationFailureHandler
      enable-auto-commit: false
    producer: # DLT! -> multiple producers: https://codingnconcepts.com/spring-boot/configure-multiple-kafka-producer/
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: de.sample.schulung.statistics.kafka.exceptions.CustomJsonSerializer
      properties:
        # do not serialize the class name into the message
        "[spring.json.add.type.headers]": false
    listener:
      ack-mode: manual
application:
  kafka:
    customer-events-topic: customer-events